services:
  postgres:
    container_name: Kokodi_db
    image: postgres
    environment:
      POSTGRES_DB: "kokodi-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-kokodi
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    ports:
      - "8001:80"