app:
  deck_multiplier: 30

auth:
  jwt:
    secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
    expiration: 86400_000

server:
  port: 8080

spring:
  application:
    name: kokodi-test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kokodi-db
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop